package uk.ac.warwick.dcs.sherlock.engine.report;

import uk.ac.warwick.dcs.sherlock.api.common.ICodeBlockGroup;
import uk.ac.warwick.dcs.sherlock.api.model.detection.DetectionType;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.*;

/**
 * Implementations of this class are used by the Report Manager to generate reports for files where plagiarism is suspected (though it can be run for any file in principle).
 */
public abstract class AbstractReportGenerator {


	public AbstractReportGenerator() {

	}

	/**
	 * Generate a report for a single file.
	 *
	 * @param persistentId The unique ID for the file in question as generated by getPersistentId() in ISourceFile.
	 * @param codeBlockGroups The ICodeBlockGroups that contain ICodeBlocks from the file whose report will be generated. Supplied by the Report Manager.
	 * @return The report itself.
	 */
	public abstract FileReport GenerateReport(long persistentId, List<? extends ICodeBlockGroup> codeBlockGroups);
}
