CREATE SCHEMA IF NOT EXISTS PUBLIC;

CREATE SEQUENCE PUBLIC.hibernate_sequence;

CREATE TABLE PUBLIC.ACCOUNT(
    ID BIGINT NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255),
    NAME VARCHAR(255)
);
ALTER TABLE PUBLIC.ACCOUNT ADD CONSTRAINT PUBLIC.CONSTRAINT_ACC_ID PRIMARY KEY(ID);

CREATE TABLE PUBLIC.DETECTOR(
    ID BIGINT NOT NULL,
    NAME VARCHAR(255),
    TEMPLATE BIGINT
);
ALTER TABLE PUBLIC.DETECTOR ADD CONSTRAINT PUBLIC.CONSTRAINT_DET_ID PRIMARY KEY(ID);

CREATE TABLE PUBLIC.PARAMETER(
    ID BIGINT NOT NULL,
    NAME VARCHAR(255),
    VALUE DOUBLE,
    POSTPROCESSING BOOLEAN,
    T_DETECTOR BIGINT
);
ALTER TABLE PUBLIC.PARAMETER ADD CONSTRAINT PUBLIC.CONSTRAINT_PARA_ID PRIMARY KEY(ID);

CREATE TABLE PUBLIC.ROLE(
    ROLE_ID BIGINT NOT NULL,
    NAME VARCHAR(255),
    ACCOUNT BIGINT
);
ALTER TABLE PUBLIC.ROLE ADD CONSTRAINT PUBLIC.CONSTRAINT_ROLE_ID PRIMARY KEY(ROLE_ID);

CREATE TABLE PUBLIC.TEMPLATE(
    ID BIGINT NOT NULL,
    IS_PUBLIC BOOLEAN,
    LANGUAGE VARCHAR(255),
    NAME VARCHAR(255),
    ACCOUNT BIGINT
);
ALTER TABLE PUBLIC.TEMPLATE ADD CONSTRAINT PUBLIC.CONSTRAINT_TEMP_ID PRIMARY KEY(ID);

CREATE TABLE PUBLIC.WORKSPACE(
    ID BIGINT NOT NULL,
    ENGINE_ID BIGINT,
    ACCOUNT BIGINT
);
ALTER TABLE PUBLIC.WORKSPACE ADD CONSTRAINT PUBLIC.CONSTRAINT_WORK_ID PRIMARY KEY(ID);

ALTER TABLE PUBLIC.ACCOUNT ADD CONSTRAINT PUBLIC.UNIQUE_EMAIL UNIQUE(EMAIL);
ALTER TABLE PUBLIC.ROLE ADD CONSTRAINT PUBLIC.ROLE_REF_ACCOUNT FOREIGN KEY(ACCOUNT) REFERENCES PUBLIC.ACCOUNT(ID) NOCHECK;
ALTER TABLE PUBLIC.DETECTOR ADD CONSTRAINT PUBLIC.DETECTOR_REF_TEMPLATE FOREIGN KEY(TEMPLATE) REFERENCES PUBLIC.TEMPLATE(ID) NOCHECK;
ALTER TABLE PUBLIC.PARAMETER ADD CONSTRAINT PUBLIC.PARAMETER_REF_DETECTOR FOREIGN KEY(T_DETECTOR) REFERENCES PUBLIC.DETECTOR(ID) NOCHECK;
ALTER TABLE PUBLIC.TEMPLATE ADD CONSTRAINT PUBLIC.TEMPLATE_REF_ACCOUNT FOREIGN KEY(ACCOUNT) REFERENCES PUBLIC.ACCOUNT(ID) NOCHECK;
ALTER TABLE PUBLIC.WORKSPACE ADD CONSTRAINT PUBLIC.WORKSPACE_REF_ACCOUNT FOREIGN KEY(ACCOUNT) REFERENCES PUBLIC.ACCOUNT(ID) NOCHECK;
